    # nixpacks.toml
    
    [phases.setup]
    # This tells Railway to install the system libraries needed to build your Python packages
    nixPkgs = ["postgresql", "gcc"]
    
    [start]
    # This is the command Railway will run to start your server AFTER the build is complete
    cmd = "gunicorn BookNexus.wsgi:application"
    